export enum RESPONSE_CODES {
  SUCCESS = 200,
  CREATED,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UN_AUTHORIZED,
  FORBIDDEN = 403,
  NOT_FOUND,
  CONFLICT = 409,
  UNSUPPORTED_MEDIATYPE = 415,
  EXPECTATION_FAILED = 417,
  UN_PROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,
}

export const MAX_REQUEST_SIZE = 1024 * 1024; // 1MB


export enum UserTypes {
  ADMIN = 1,
  USER
}

